// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOErA7MuexznC9WHCTAlSODXjbKn_OYHA',
    appId: '1:444811097285:web:e3f34933dfc70c2ea8ecac',
    messagingSenderId: '444811097285',
    projectId: 'helloworld-70512',
    authDomain: 'helloworld-70512.firebaseapp.com',
    storageBucket: 'helloworld-70512.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KD4Lx0I0EriSmceDnVecT2paqsq_gRY',
    appId: '1:444811097285:android:ef6f14f2f8a7194aa8ecac',
    messagingSenderId: '444811097285',
    projectId: 'helloworld-70512',
    storageBucket: 'helloworld-70512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERgqsxNkh3u0YYRYxaVby63mK0ryoW30',
    appId: '1:444811097285:ios:314f7782c182a6e5a8ecac',
    messagingSenderId: '444811097285',
    projectId: 'helloworld-70512',
    storageBucket: 'helloworld-70512.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAERgqsxNkh3u0YYRYxaVby63mK0ryoW30',
    appId: '1:444811097285:ios:314f7782c182a6e5a8ecac',
    messagingSenderId: '444811097285',
    projectId: 'helloworld-70512',
    storageBucket: 'helloworld-70512.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOErA7MuexznC9WHCTAlSODXjbKn_OYHA',
    appId: '1:444811097285:web:416c3e6a893d99cfa8ecac',
    messagingSenderId: '444811097285',
    projectId: 'helloworld-70512',
    authDomain: 'helloworld-70512.firebaseapp.com',
    storageBucket: 'helloworld-70512.firebasestorage.app',
  );
}
